CREATE DATABASE logeoFastApi;
USE logeoFastApi;

CREATE TABLE MODULO (
	CVE_MODULO VARCHAR(20) NOT NULL,
	NAME_MODULO VARCHAR(20) NOT NULL,
	DIRECCION_URL VARCHAR(40) NOT NULL,
	STATUS_MODULO INTEGER NOT NULL,
	CREACION_MODULO VARCHAR(20) NOT NULL,
	MODIFICACION_MODULO VARCHAR(20) NOT NULL,
	FECHA_CREACION_MOD DATE NOT NULL,
	FECHA_MODIFICACION_MOD DATE NOT NULL,
	DESCRIPTION_MOD VARCHAR(40) NULL
);

CREATE UNIQUE INDEX XPKMODULO ON MODULO (CVE_MODULO ASC);

ALTER TABLE MODULO
	ADD CONSTRAINT XPKMODULO PRIMARY KEY (CVE_MODULO);

CREATE TABLE PERMISOS (
	CVE_PERMISO VARCHAR(20) NOT NULL,
	NAME_PERMISO VARCHAR(20) NOT NULL,
	STATUS_PERMISOS INTEGER NOT NULL,
	MODIFICACION_PERMISO VARCHAR(20) NULL,
	CREACION_PERMISOS VARCHAR(20) NULL,
	FECHA_CREACION_PER DATE NOT NULL,
	FECHA_MODIFICACION_PER DATE NOT NULL,
	CVE_ROL VARCHAR(20) NOT NULL,
	CVE_MODULO VARCHAR(20) NOT NULL
);

CREATE UNIQUE INDEX XPKPERMISOS ON PERMISOS (
	CVE_PERMISO ASC,
	CVE_ROL ASC,
	CVE_MODULO ASC
);

ALTER TABLE PERMISOS
	ADD CONSTRAINT XPKPERMISOS PRIMARY KEY (CVE_PERMISO, CVE_ROL, CVE_MODULO);

CREATE TABLE ROL (
	CVE_ROL VARCHAR(20) NOT NULL,
	NAME_ROL VARCHAR(20) NOT NULL,
	STATUS INTEGER NOT NULL,
	CREACION_ROL VARCHAR(20) NOT NULL,
	MODIFICACION_ROL VARCHAR(20) NOT NULL,
	FECHA_CREACION_ROL DATE NOT NULL,
	FECHA_MODIFICACION_ROL DATE NOT NULL
);

CREATE UNIQUE INDEX XPKROL ON ROL (CVE_ROL ASC);

ALTER TABLE ROL
	ADD CONSTRAINT XPKROL PRIMARY KEY (CVE_ROL);

CREATE TABLE USUARIO
(
	CVE_USER  int primary key AUTO_INCREMENT,
	NAME_USER  varchar(200)  NOT NULL ,
	CONTRASEÑA  varchar(200)  NOT NULL ,
	EMAIL_USER  varchar(100)  not NULL ,
	STATUS_USER  integer  NOT NULL DEFAULT 1,
	CVE_ROL  varchar(100)  NOT NULL DEFAULT '1',
	CREACION_USER  char varying(100)  NOT NULL DEFAULT 'system' ,
	MODIFICACION_USER  char varying(100)  NOT NULL default 'SYSTEM',
	FECHA_MODIFICACION_USER  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
	TOKEN_USUARIO varchar(200) default "001"
);

ALTER TABLE USUARIO
	ADD CONSTRAINT  R_8 FOREIGN KEY (CVE_ROL) REFERENCES ROL(CVE_ROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;



ALTER TABLE PERMISOS
	ADD CONSTRAINT R_10 FOREIGN KEY (CVE_ROL) REFERENCES ROL(CVE_ROL);

ALTER TABLE PERMISOS
	ADD CONSTRAINT R_11 FOREIGN KEY (CVE_MODULO) REFERENCES MODULO(CVE_MODULO);


